# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false
ffi = true
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "prague"
fuzz = { runs = 100_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 0
out = "out"
script = "script"
solc = "0.8.30"
src = "src"
test = "test"
fs_permissions = [{ access = "read", path = "./" }, { access = "read-write", path = "./svgs" }]

[profile.ci]
fuzz = { runs = 1_000_000 }
verbosity = 4

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
ignore = ["./test/llm-tests", "./src/interface/Sculpture.sol"]

[rpc_endpoints]
localhost = "http://localhost:8545"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
